### ISSUE TITLE
BE story - filter by target audience 

### ISSUE THREAD

**Issue by yarelismartin** [FletcherJMoore/Fan-Fusion-BE#26]
### **Description**
Implement the [ filter by target audience ] route for the [story ] entity.
- **Entity**: story 
- **Action**:  filter by target audience 
---
### **Task Breakdown**
- [x] Include endpoint in its API file within the APIs folder
- [x] Define the route path.
- [x] Handle request validation and data persistence.
- [x] Implement error handling and appropriate status codes.
- [x] Test on Swagger
---
### **Request**
- **HTTP Method**:
- **Path**: `/api/[entity]/[action]`
- **Body**:
```
 ```
### **Response**
- **Status Code**:
- **Body**:
```

**Comment by FletcherJMoore** [comment]
Was able to get this call up and running in swagger
